/**
 * ristretto255.ts — Issue #1186: prime-order group for ZK ticket attestation.
 *
 * A self-contained ristretto255 implementation (RFC 9496) over `BigInt`. This
 * is the mobile counterpart of the Rust `curve25519-dalek` usage in
 * `server/src/utils/zkp_verifier.rs`; a proof generated here must verify there,
 * so every encoding below follows RFC 9496 exactly rather than conveniently.
 *
 * ## Why hand-rolled rather than a library
 *
 * `@noble/curves` would be the obvious choice, and is the right one the moment
 * the mobile app takes a dependency on it for something else. It is not here
 * yet, and adding it means a lockfile change for one feature. Everything this
 * module needs — one group, three operations — is ~400 lines of well-specified
 * arithmetic, and the conformance vectors in `__tests__/proofGenerator.test.ts`
 * are generated by the Rust verifier, so the two implementations are pinned to
 * each other rather than to my reading of the spec.
 *
 * ## Why ristretto255 and not raw Ed25519
 *
 * Ed25519 has cofactor 8: eight distinct encodings represent the same logical
 * point, and small-order points exist. A ring proof over a cofactor group is a
 * minefield — an attacker can add a small-order component to a nullifier and
 * produce a second valid encoding of the "same" spend, defeating double-spend
 * detection. Ristretto quotients that away and gives a prime-order group with
 * a canonical encoding, which is exactly what the protocol assumes.
 *
 * ## Constants are derived, not transcribed
 *
 * Every curve constant below is computed at module load from `p` and the two
 * integers in the definition of `d`. Transcribing 32-byte constants by hand is
 * the single most common way an implementation like this ends up subtly and
 * silently wrong, so we do not do it. Load cost is a handful of modular
 * exponentiations, once.
 *
 * ## Timing
 *
 * Not constant-time, and cannot be: `BigInt` arithmetic in a JS engine is
 * inherently data-dependent. The exposure is a local attacker who can time
 * proof generation on the attendee's own unlocked device — which is a weaker
 * position than simply reading the ticket secret out of the vault. The server
 * verifier, where untrusted input meets secret-independent code, uses dalek's
 * variable-time paths deliberately and safely; see the Rust module docs.
 */

// ── Small BigInt constants ───────────────────────────────────────────────────
//
// Spelled out rather than written as `0n` literals so the module compiles
// under a pre-ES2020 `target` as well.

const ZERO = BigInt(0);
const ONE = BigInt(1);
const TWO = BigInt(2);
const THREE = BigInt(3);
const FOUR = BigInt(4);
const FIVE = BigInt(5);
const EIGHT = BigInt(8);

// ── Field arithmetic modulo p = 2^255 - 19 ───────────────────────────────────

/** The field prime, 2^255 − 19. */
export const P = (ONE << BigInt(255)) - BigInt(19);

/** Reduces into `[0, P)`, accepting negative inputs. */
export function feMod(x: bigint): bigint {
  const r = x % P;
  return r < ZERO ? r + P : r;
}

/** Modular addition. */
export function feAdd(a: bigint, b: bigint): bigint {
  return feMod(a + b);
}

/** Modular subtraction. */
export function feSub(a: bigint, b: bigint): bigint {
  return feMod(a - b);
}

/** Modular multiplication. */
export function feMul(a: bigint, b: bigint): bigint {
  return feMod(a * b);
}

/** Modular squaring. */
export function feSqr(a: bigint): bigint {
  return feMod(a * a);
}

/** Modular negation. */
export function feNeg(a: bigint): bigint {
  return feMod(-a);
}

/** Modular exponentiation by square-and-multiply. */
export function fePow(base: bigint, exponent: bigint): bigint {
  let result = ONE;
  let b = feMod(base);
  let e = exponent;
  while (e > ZERO) {
    if (e & ONE) result = feMul(result, b);
    b = feSqr(b);
    e >>= ONE;
  }
  return result;
}

/** Modular inverse via Fermat's little theorem. */
export function feInv(a: bigint): bigint {
  return fePow(a, P - TWO);
}

/**
 * A field element is "negative" when the low bit of its canonical
 * little-endian encoding is set (RFC 9496 §4.1). This is the sign convention
 * the whole encoding depends on.
 */
export function feIsNegative(a: bigint): boolean {
  return (feMod(a) & ONE) === ONE;
}

/** `|a|` under the sign convention above. */
export function feAbs(a: bigint): bigint {
  return feIsNegative(a) ? feNeg(a) : feMod(a);
}

// ── Derived curve constants ──────────────────────────────────────────────────

/** √−1. Exists because p ≡ 5 (mod 8), where it equals 2^((p−1)/4). */
export const SQRT_M1 = fePow(TWO, (P - ONE) / FOUR);

/** The Edwards curve parameter d = −121665/121666. */
export const D = feMul(feNeg(BigInt(121665)), feInv(BigInt(121666)));

/**
 * Principal square root, or `null` when the input is not a square.
 *
 * For p ≡ 5 (mod 8) the candidate is `x^((p+3)/8)`; if it squares to `−x`
 * instead of `x`, multiplying by √−1 corrects it.
 */
export function feSqrt(x: bigint): bigint | null {
  const v = feMod(x);
  if (v === ZERO) return ZERO;
  let candidate = fePow(v, (P + THREE) / EIGHT);
  if (feSqr(candidate) !== v) {
    candidate = feMul(candidate, SQRT_M1);
  }
  if (feSqr(candidate) !== v) return null;
  return candidate;
}

/**
 * The non-negative square root of `a·d − 1` = `a − d` = `−d − 1` (a = −1).
 *
 * Both constants below come from this one value, but — and this is the trap —
 * they use **opposite roots**. In the reference implementation
 * `SQRT_AD_MINUS_ONE * INVSQRT_A_MINUS_D` is −1, not 1: `SQRT_AD_MINUS_ONE` is
 * the negative (odd) root while `INVSQRT_A_MINUS_D` inverts the non-negative
 * one. They are not inverses of each other despite the names suggesting it.
 *
 * Getting this wrong is invisible in the round-trip tests — encoding and
 * decoding stay self-consistent — and shows up only as an Elligator output
 * that disagrees with the verifier. The conformance vectors are what caught it.
 */
const AD_MINUS_ONE_ROOT = (() => {
  const root = feSqrt(feSub(feNeg(D), ONE));
  if (root === null) {
    throw new Error('ristretto255: a·d − 1 is not a square; field constants are wrong');
  }
  return feAbs(root);
})();

/** √(a·d − 1), taking the negative root. Used by the Elligator map. */
export const SQRT_AD_MINUS_ONE = feNeg(AD_MINUS_ONE_ROOT);

/** 1/√(a − d), inverting the non-negative root. Used when encoding. */
export const INVSQRT_A_MINUS_D = feInv(AD_MINUS_ONE_ROOT);

/** 1 − d². */
export const ONE_MINUS_D_SQ = feSub(ONE, feSqr(D));

/** (d − 1)². */
export const D_MINUS_ONE_SQ = feSqr(feSub(D, ONE));

/**
 * RFC 9496 `SQRT_RATIO_M1(u, v)`: returns √(u/v), or √(i·u/v) when u/v is not
 * a square, together with a flag saying which happened.
 *
 * This one primitive carries the encoding, the decoding, and the Elligator
 * map. Everything else is bookkeeping around it.
 */
export function feSqrtRatioM1(u: bigint, v: bigint): { wasSquare: boolean; result: bigint } {
  const uu = feMod(u);
  const vv = feMod(v);

  const v3 = feMul(feSqr(vv), vv);
  const v7 = feMul(feSqr(v3), vv);
  let r = feMul(feMul(uu, v3), fePow(feMul(uu, v7), (P - FIVE) / EIGHT));
  const check = feMul(vv, feSqr(r));

  const negU = feNeg(uu);
  const correctSignSqrt = check === uu;
  const flippedSignSqrt = check === negU;
  const flippedSignSqrtI = check === feMul(negU, SQRT_M1);

  if (flippedSignSqrt || flippedSignSqrtI) {
    r = feMul(r, SQRT_M1);
  }
  r = feAbs(r);

  return { wasSquare: correctSignSqrt || flippedSignSqrt, result: r };
}

// ── Extended twisted Edwards points ──────────────────────────────────────────

/**
 * A point in extended coordinates (X : Y : Z : T), where x = X/Z, y = Y/Z and
 * T = XY/Z. Ristretto treats points differing by a cofactor element as equal,
 * so two distinct `ExtendedPoint`s can encode identically — always compare
 * with {@link pointEquals}, never field-by-field.
 */
export interface ExtendedPoint {
  X: bigint;
  Y: bigint;
  Z: bigint;
  T: bigint;
}

/** The group identity. */
export const IDENTITY: ExtendedPoint = { X: ZERO, Y: ONE, Z: ONE, T: ZERO };

/**
 * The ristretto255 basepoint `G`, recovered from y = 4/5.
 *
 * Derived rather than transcribed, as with everything else here. The x root is
 * pinned to the even one, matching the canonical Ed25519 basepoint.
 */
export const BASEPOINT: ExtendedPoint = (() => {
  const y = feMul(FOUR, feInv(FIVE));
  const yy = feSqr(y);
  // x² = (y² − 1) / (d·y² + 1)
  const xx = feMul(feSub(yy, ONE), feInv(feAdd(feMul(D, yy), ONE)));
  const root = feSqrt(xx);
  if (root === null) {
    throw new Error('ristretto255: basepoint recovery failed; field constants are wrong');
  }
  const x = feIsNegative(root) ? feNeg(root) : root;
  return { X: x, Y: y, Z: ONE, T: feMul(x, y) };
})();

/** Point addition, `add-2008-hwcd-3` for a = −1. Unified: valid for doubling. */
export function pointAdd(p1: ExtendedPoint, p2: ExtendedPoint): ExtendedPoint {
  const a = feMul(feSub(p1.Y, p1.X), feSub(p2.Y, p2.X));
  const b = feMul(feAdd(p1.Y, p1.X), feAdd(p2.Y, p2.X));
  const c = feMul(feMul(p1.T, TWO), feMul(D, p2.T));
  const d = feMul(feMul(p1.Z, TWO), p2.Z);
  const e = feSub(b, a);
  const f = feSub(d, c);
  const g = feAdd(d, c);
  const h = feAdd(b, a);
  return {
    X: feMul(e, f),
    Y: feMul(g, h),
    Z: feMul(f, g),
    T: feMul(e, h),
  };
}

/** Point doubling, `dbl-2008-hwcd` for a = −1. */
export function pointDouble(p1: ExtendedPoint): ExtendedPoint {
  const a = feSqr(p1.X);
  const b = feSqr(p1.Y);
  const c = feMul(TWO, feSqr(p1.Z));
  const d = feNeg(a);
  const e = feSub(feSub(feSqr(feAdd(p1.X, p1.Y)), a), b);
  const g = feAdd(d, b);
  const f = feSub(g, c);
  const h = feSub(d, b);
  return {
    X: feMul(e, f),
    Y: feMul(g, h),
    Z: feMul(f, g),
    T: feMul(e, h),
  };
}

/** Point negation. */
export function pointNeg(p1: ExtendedPoint): ExtendedPoint {
  return { X: feNeg(p1.X), Y: p1.Y, Z: p1.Z, T: feNeg(p1.T) };
}

/** Point subtraction. */
export function pointSub(p1: ExtendedPoint, p2: ExtendedPoint): ExtendedPoint {
  return pointAdd(p1, pointNeg(p2));
}

/**
 * Scalar multiplication by a fixed 4-bit window.
 *
 * Windowing roughly halves the work versus plain double-and-add, which matters
 * because a ring proof over `n` members runs O(n) of these on a phone.
 */
export function pointMul(point: ExtendedPoint, scalar: bigint): ExtendedPoint {
  let k = scalar;
  if (k < ZERO) {
    return pointMul(pointNeg(point), -k);
  }
  k = k % L;
  if (k === ZERO) return IDENTITY;

  // Precompute [0]P, [1]P, ..., [15]P.
  const table: ExtendedPoint[] = [IDENTITY, point];
  for (let i = 2; i < 16; i++) {
    table.push(pointAdd(table[i - 1], point));
  }

  // Walk nibbles most-significant first.
  const nibbles: number[] = [];
  let remaining = k;
  const SIXTEEN = BigInt(16);
  while (remaining > ZERO) {
    nibbles.push(Number(remaining % SIXTEEN));
    remaining /= SIXTEEN;
  }

  let acc = IDENTITY;
  let started = false;
  for (let i = nibbles.length - 1; i >= 0; i--) {
    if (started) {
      acc = pointDouble(pointDouble(pointDouble(pointDouble(acc))));
    }
    const nibble = nibbles[i];
    if (nibble !== 0) {
      acc = pointAdd(acc, table[nibble]);
      started = true;
    }
  }
  return acc;
}

/** Computes `a·P + b·Q` in one pass. */
export function pointMulAdd(
  p1: ExtendedPoint,
  a: bigint,
  p2: ExtendedPoint,
  b: bigint
): ExtendedPoint {
  return pointAdd(pointMul(p1, a), pointMul(p2, b));
}

/**
 * Ristretto equality (RFC 9496 §4.3.3).
 *
 * Two representatives are the same group element when either cross-product
 * relation holds — comparing coordinates directly would report equal points as
 * different.
 */
export function pointEquals(p1: ExtendedPoint, p2: ExtendedPoint): boolean {
  const a = feMul(p1.X, p2.Y) === feMul(p2.X, p1.Y);
  const b = feMul(p1.Y, p2.Y) === feMul(p1.X, p2.X);
  return a || b;
}

/** Whether a point is the group identity. */
export function pointIsIdentity(p1: ExtendedPoint): boolean {
  return pointEquals(p1, IDENTITY);
}

// ── Byte conversion ──────────────────────────────────────────────────────────

/** Decodes 32 little-endian bytes into a BigInt. */
export function bytesToBigIntLE(bytes: Uint8Array): bigint {
  let result = ZERO;
  for (let i = bytes.length - 1; i >= 0; i--) {
    result = (result << EIGHT) | BigInt(bytes[i]);
  }
  return result;
}

/** Encodes a BigInt as `length` little-endian bytes. */
export function bigIntToBytesLE(value: bigint, length: number): Uint8Array {
  const out = new Uint8Array(length);
  let v = value;
  const BYTE_MASK = BigInt(0xff);
  for (let i = 0; i < length; i++) {
    out[i] = Number(v & BYTE_MASK);
    v >>= EIGHT;
  }
  return out;
}

// ── Ristretto encoding ───────────────────────────────────────────────────────

/**
 * Compresses a point to its canonical 32-byte ristretto encoding
 * (RFC 9496 §4.3.2).
 */
export function pointCompress(point: ExtendedPoint): Uint8Array {
  const { X: x0, Y: y0, Z: z0, T: t0 } = point;

  const u1 = feMul(feAdd(z0, y0), feSub(z0, y0));
  const u2 = feMul(x0, y0);

  const { result: invsqrt } = feSqrtRatioM1(ONE, feMul(u1, feSqr(u2)));

  const den1 = feMul(invsqrt, u1);
  const den2 = feMul(invsqrt, u2);
  const zInv = feMul(feMul(den1, den2), t0);

  const ix0 = feMul(x0, SQRT_M1);
  const iy0 = feMul(y0, SQRT_M1);
  const enchantedDenominator = feMul(den1, INVSQRT_A_MINUS_D);

  const rotate = feIsNegative(feMul(t0, zInv));

  const x = rotate ? iy0 : x0;
  let y = rotate ? ix0 : y0;
  const denInv = rotate ? enchantedDenominator : den2;

  if (feIsNegative(feMul(x, zInv))) {
    y = feNeg(y);
  }

  const s = feAbs(feMul(denInv, feSub(z0, y)));
  return bigIntToBytesLE(s, 32);
}

/**
 * Decompresses a 32-byte ristretto encoding (RFC 9496 §4.3.1), or returns
 * `null` if the bytes are not a valid canonical encoding.
 *
 * Rejects non-canonical field encodings outright. Accepting them would break
 * the one-encoding-per-point property that the nullifier store relies on for
 * double-spend detection.
 */
export function pointDecompress(bytes: Uint8Array): ExtendedPoint | null {
  if (bytes.length !== 32) return null;

  const s = bytesToBigIntLE(bytes);
  // Canonical: re-encoding must reproduce the input, and s must be non-negative.
  if (s >= P) return null;
  if (feIsNegative(s)) return null;

  const ss = feSqr(s);
  const u1 = feSub(ONE, ss);
  const u2 = feAdd(ONE, ss);
  const u2Sqr = feSqr(u2);

  const v = feSub(feNeg(feMul(D, feSqr(u1))), u2Sqr);

  const { wasSquare, result: invsqrt } = feSqrtRatioM1(ONE, feMul(v, u2Sqr));

  const denX = feMul(invsqrt, u2);
  const denY = feMul(feMul(invsqrt, denX), v);

  const x = feAbs(feMul(feMul(TWO, s), denX));
  const y = feMul(u1, denY);
  const t = feMul(x, y);

  if (!wasSquare || feIsNegative(t) || y === ZERO) return null;

  return { X: x, Y: y, Z: ONE, T: t };
}

// ── Elligator / hash-to-group ────────────────────────────────────────────────

/** The one-way map of RFC 9496 §4.3.4, applied to a single field element. */
function elligator(t: bigint): ExtendedPoint {
  const r = feMul(SQRT_M1, feSqr(t));
  const u = feMul(feAdd(r, ONE), ONE_MINUS_D_SQ);

  let c = feNeg(ONE);
  const v = feMul(feSub(c, feMul(r, D)), feAdd(r, D));

  const { wasSquare, result: sqrtResult } = feSqrtRatioM1(u, v);

  let s = sqrtResult;
  if (!wasSquare) {
    s = feNeg(feAbs(feMul(sqrtResult, t)));
    c = r;
  }

  const n = feSub(feMul(feMul(c, feSub(r, ONE)), D_MINUS_ONE_SQ), v);

  const w0 = feMul(feMul(TWO, s), v);
  const w1 = feMul(n, SQRT_AD_MINUS_ONE);
  const w2 = feSub(ONE, feSqr(s));
  const w3 = feAdd(ONE, feSqr(s));

  return {
    X: feMul(w0, w3),
    Y: feMul(w2, w1),
    Z: feMul(w1, w3),
    T: feMul(w0, w2),
  };
}

/**
 * Maps 64 uniformly random bytes to a group element — the equivalent of
 * dalek's `RistrettoPoint::from_uniform_bytes`.
 *
 * The two halves are mapped separately and added, which is what makes the
 * output distribution statistically close to uniform. Each half is a field
 * element with its high bit masked off, matching dalek's `FieldElement`
 * decoding.
 */
export function pointFromUniformBytes(bytes: Uint8Array): ExtendedPoint {
  if (bytes.length !== 64) {
    throw new Error(`pointFromUniformBytes: expected 64 bytes, got ${bytes.length}`);
  }

  const half1 = bytes.slice(0, 32);
  const half2 = bytes.slice(32, 64);
  // Mask bit 255, as the reference field decoding does, then reduce.
  half1[31] &= 0x7f;
  half2[31] &= 0x7f;

  const r0 = feMod(bytesToBigIntLE(half1));
  const r1 = feMod(bytesToBigIntLE(half2));

  return pointAdd(elligator(r0), elligator(r1));
}

// ── Scalar arithmetic modulo the group order ─────────────────────────────────

/** The prime group order, ℓ = 2^252 + 27742317777372353535851937790883648493. */
export const L = (ONE << BigInt(252)) + BigInt('27742317777372353535851937790883648493');

/** Reduces into `[0, L)`, accepting negative inputs. */
export function scalarMod(x: bigint): bigint {
  const r = x % L;
  return r < ZERO ? r + L : r;
}

/** Scalar addition mod ℓ. */
export function scalarAdd(a: bigint, b: bigint): bigint {
  return scalarMod(a + b);
}

/** Scalar subtraction mod ℓ. */
export function scalarSub(a: bigint, b: bigint): bigint {
  return scalarMod(a - b);
}

/** Scalar multiplication mod ℓ. */
export function scalarMul(a: bigint, b: bigint): bigint {
  return scalarMod(a * b);
}

/**
 * Wide reduction of 64 bytes into a scalar — dalek's
 * `Scalar::from_bytes_mod_order_wide`. Uniform mod ℓ, unlike a bare 32-byte
 * reduction, which is measurably biased.
 */
export function scalarFromBytesWide(bytes: Uint8Array): bigint {
  if (bytes.length !== 64) {
    throw new Error(`scalarFromBytesWide: expected 64 bytes, got ${bytes.length}`);
  }
  return scalarMod(bytesToBigIntLE(bytes));
}

/** Canonical 32-byte little-endian scalar encoding. */
export function scalarToBytes(scalar: bigint): Uint8Array {
  return bigIntToBytesLE(scalarMod(scalar), 32);
}

/** Decodes a canonical 32-byte scalar, rejecting anything ≥ ℓ. */
export function scalarFromBytes(bytes: Uint8Array): bigint | null {
  if (bytes.length !== 32) return null;
  const value = bytesToBigIntLE(bytes);
  return value >= L ? null : value;
}
