services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: eventopry_server
    environment:
      PORT: 3001
      DATABASE_URL: postgres://user:password@postgres:5432/eventopry
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: eventopry_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventopry
    ports:
      - "5432:5432"
    volumes:
      - eventopry_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eventopry"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: eventopry_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: eventopry_jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

volumes:
  eventopry_postgres_data:
