import { MetadataRoute } from "next";

/**
 * Crawl directives for search engines (/robots.txt).
 *
 * Generated by the App Router at build time from this file, so the rules stay
 * in the codebase rather than in a hand-maintained static file that drifts.
 *
 * The base URL matches `metadataBase` in `app/layout.tsx` so the advertised
 * sitemap and the canonical URLs point at the same origin.
 */
const BASE_URL = "https://agora.events";

/**
 * Routes that must not be indexed.
 *
 * - `/api/` returns JSON, never a landing page, and some routes are
 *   side-effecting.
 * - `/__visual_fixtures__` renders component fixtures for visual regression
 *   tests; indexing it would surface fragments of the UI as search results.
 * - `/auth` and `/settings` are per-user and behind a session, so a crawler
 *   only ever sees a redirect or an empty shell.
 */
const DISALLOWED = ["/api/", "/__visual_fixtures__", "/auth", "/settings"];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: DISALLOWED,
    },
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}
