use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
/// Error codes returned by the Event Registry contract.
pub enum EventRegistryError {
    EventAlreadyExists = 1,
    EventNotFound = 2,
    Unauthorized = 3,
    InvalidAddress = 4,
    InvalidFeePercent = 5,
    EventInactive = 6,
    NotInitialized = 7,
    AlreadyInitialized = 8,
    InvalidMetadataCid = 9,
    MaxSupplyExceeded = 10,
    SupplyOverflow = 11,
    TierLimitExceeds = 13,
    TierNotFound = 14,
    TierSoldOut = 15,
    SupplyUnderflow = 16,
    InvalidQuantity = 17,
    OrganizerBlacklisted = 18,
    OrgNotBlacklisted = 19,
    InvalidResaleCapBps = 20,
    InvalidPromoBps = 21,
    EventCancelled = 22,
    EventAlreadyCanceled = 23,
    InvalidGracePeriod = 24,
    EventIsActive = 25,
    AlreadyStaked = 26,
    NotStaked = 27,
    InvalidStakeAmount = 29,
    StakingNotConfigured = 30,
    NoRewardsAvailable = 31,
    InvalidRewardAmount = 32,
    InvalidThreshold = 36,
    PropAlreadyExecuted = 38,
    EventNotEnded = 39,
    InvalidMilestonePlan = 41,
    InvalidTags = 43,
    ProposalExpired = 44,
    MultisigError = 47,
    PropAlreadyCanceled = 49,
    PerUserLimitExceeded = 60,
    InvalidDeadline = 61,
    AlreadyOnWaitlist = 75,
    NotOnWaitlist = 76,
    TooManyTiers = 80,
    TokenNotAccepted = 82,
    DisputeNotFound = 83,
    DisputeNotOpen = 84,
    AlreadyVoted = 85,
    NotTicketHolder = 86,
    ReplayAttackDetected = 87,
    InsufficientSignatures = 88,
}
