/**
 * proofGenerator.test.ts — Issue #1186.
 *
 * ## The conformance vectors
 *
 * A proof is only useful if the Rust verifier accepts it, and nothing in CI
 * runs Rust and TypeScript in the same process. So the contract between the
 * two implementations is pinned by vectors instead: the hex strings in
 * `VECTORS` below were produced by the reference prover in
 * `server/src/utils/zkp_verifier.rs`, and `conformance_proof_is_valid` there
 * asserts the same proof verifies.
 *
 * Both provers are driven by the identical deterministic scalar stream
 * (`vectorRng`, mirroring `VectorRng` in the Rust `conformance` module), so
 * they must emit byte-identical proofs. If this file goes red, the two
 * implementations have diverged and real check-ins would fail at the gate.
 *
 * Regenerate with:
 * `cargo test -p eventopry-server zkp_conformance -- --ignored --nocapture`
 */

import {
  commit,
  computeNullifier,
  DEFAULT_EPOCH,
  encodeProof,
  findWitnessIndex,
  fromHex,
  generateCheckinProof,
  generatorG,
  generatorH,
  hashToScalar,
  leafHash,
  merkleRoot,
  merkleRootOfCommitments,
  nullifierBase,
  pointCompress,
  PROOF_VERSION,
  prove,
  ProverRng,
  ringFromHex,
  secretScalar,
  ticketScalar,
  tierByte,
  tierMinRing,
  toHex,
  verifyLocally,
  type AttestationTier,
  type ProofContext,
  type RingMember,
} from '../proofGenerator';

// ── Vectors generated by the Rust reference implementation ───────────────────

const VECTORS = {
  eventId: 'evt_conformance',
  epoch: DEFAULT_EPOCH,
  tier: 'age21plus' as AttestationTier,
  ringSize: 8,
  witnessIndex: 3,
  generatorH: '7831785b2a725054a571b6b7af6f9060c4c2efd03ee80ce9d83a98cb549a0144',
  nullifierBase: 'f202b099527f901f0222ad506e82134168344fa8a15983fb0f9b44b781e09b3c',
  commitments: [
    '46948079a2bdf6d0122b9f51fe932ddb947f4ac2d4035aaef41ddf1d79d75e28',
    'f85ce17433e7e9b912ed05b507bf0702c4d9c36ec23545dc550a6f6bc0860b41',
    'fcba2c374d45157e2bd32769de36dcd8c49b1d71621fe0837c713d47140e1148',
    '32885c6205bb3c9499cb9c825daeffbe2cb4e0c00267b54f40e33cf657494f5e',
    'dc66fd5201a27be0d1b96adbfe08c81e44440c4a26257e34aa2185fb0404222d',
    '0cc1927cf415d7420e1df22d29b71b20ca2f3886e2715bc0b5945c55e5cb975c',
    '0e5fa6194fd80bb7f7cf20c8b0386e79879d5b8df87a95617498a3f5f6b6c659',
    '78bd8b8a1972d0182db3b3953fbc496552ed91898fe39d435193166bb875d765',
  ],
  merkleRoot: '3ef9f3f04156e6fe61af3d69227278d62f2b30d4ae5bb160c042b42472e23621',
  nullifier: '8cd94a4cf3cdf57ea9f3f53bc1cfadea183bfc1a389a2553b32bb24f8236301f',
  proof:
    '010100088cd94a4cf3cdf57ea9f3f53bc1cfadea183bfc1a389a2553b32bb24f8236301f' +
    '28eba2f5e2942b5467a633548d6f57e9631b0c2cd6ffa4254e34c33ef3d97c0a' +
    'de5b5e24388d4817bf786308e73aae6c42d98b7c65c9b654bd10aa0458b7070c' +
    '8aa1c1697f1c647d4f767a0fc4112e806d601016981f3539a4b4ce3a74d4000d' +
    'adf52190a40d8f38c2530c2a148a8bf62d49c5c54af6897000d722dfb9582c0e' +
    'fb0879e3bddb84fa90645baa61778467b3080c2c6d9c7d49f8f3452196da6a05' +
    'e511b83d37437a6caf235c0a1f2e0ebeb931f3a481dc80ee021693370de4fb0c' +
    'd10971355fa23f695ddeac22cfdb579d4572fb97c97ee02f497dbf515eedac05' +
    '08a52c54fb6f4856d8c74547fc164da1486900a1d9d3bba3480392f1023c8803' +
    'f2c2b75ce509fa7f71451b5938ec8f07277b51f21d913ccbaec5e87ec1853e08' +
    'ca8ee5b140cb3f29a3ada2270acc45e1768c5d57b83757e79f0eed1085213d0c' +
    'bf608b105005b2466bbdca3d24c27c66a5d52827325b4ae75374713ab192f607' +
    '019c741c1035697f76f7cc598fb0493922b5af3ec2a628cfd1d5197ab794c70f' +
    'ace60e27791410344ea2e7737990e18de1cf54aa6ebf78e535a21baf5b2a7e0b' +
    'e7c0493f64ab60124531265a64a083c120831124ee00424784cb55066e8d2300' +
    '825f5f1b446f548b16865671bb78966ae29656cae478cb4ccbf51ea7f7f22e07' +
    'd5e1b27e53629af30c5557c90e73cfb70046a1d0fc4042b73b66f2fcaff24604' +
    'e7b92c5ae79389bc77bfe5471936dc1a60fc10dc30a3de198b8f9894d512980f' +
    '5a078371fc5cefc3b708e85208e736e0429ca86ed6af02fffd3dcf6628c33a06' +
    'e153dc114a8027a66055c881767d53c4f9ee553a9990532a94d118514133b306' +
    'c3e090e53a4c15d7cd33c99f743ffeafb5c51bdc41a1ae03bc6e97ecaaf95007' +
    '81c52a82ee9a74246d2bb23d9fa9897224c04032f5e1877d74b4b4a87c84c40f' +
    '83b21d7eddd4c75f139214064e65116046a14ee4810c004ad7cfadbc15d25d08' +
    '249790381dd768ae2987e1fa0592f725263fe054aa1c240ec4f442019327c408' +
    '71e1be8ac39dab4bbd7f692d0f86e2b5c66d829ae39759201b9beda22b93a60d',
};

const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);

/**
 * The deterministic scalar stream shared with the Rust test suite.
 *
 * Emphatically not a CSPRNG. Its only purpose is to make the two prover
 * implementations produce identical output so they can be compared.
 */
function vectorRng(label: string): ProverRng {
  let counter = 0;
  return {
    nextScalar(): bigint {
      const encoded = new Uint8Array(8);
      let value = BigInt(counter);
      const BYTE = BigInt(0xff);
      const EIGHT = BigInt(8);
      for (let i = 7; i >= 0; i--) {
        encoded[i] = Number(value & BYTE);
        value >>= EIGHT;
      }
      counter += 1;
      return hashToScalar('eventopry/zkp/v1/test-rng', [utf8(label), encoded]);
    },
  };
}

/** Rebuilds the exact fixture the Rust conformance module builds. */
function buildFixture(): {
  ring: RingMember[];
  ringHex: string[];
  witness: { index: number; ticket: bigint; secret: bigint };
  ctx: ProofContext;
} {
  const ringHex: string[] = [];
  let witness = { index: VECTORS.witnessIndex, ticket: BigInt(0), secret: BigInt(0) };

  for (let i = 0; i < VECTORS.ringSize; i++) {
    const ticket = ticketScalar(`EVENTOPRY-TICKET-${String(i).padStart(3, '0')}`);
    const secret = hashToScalar('eventopry/zkp/v1/secret-scalar', [utf8(`conformance-secret-${i}`)]);
    if (i === VECTORS.witnessIndex) witness = { index: i, ticket, secret };
    ringHex.push(toHex(pointCompress(commit(ticket, secret))));
  }

  const ring = ringFromHex(ringHex);
  const ctx: ProofContext = {
    eventId: VECTORS.eventId,
    epoch: VECTORS.epoch,
    tier: VECTORS.tier,
    merkleRoot: merkleRootOfCommitments(ring.map((m) => m.compressed)),
    ring,
  };
  return { ring, ringHex, witness, ctx };
}

describe('public parameters match the Rust verifier', () => {
  it('derives the same second generator H', () => {
    expect(toHex(pointCompress(generatorH()))).toBe(VECTORS.generatorH);
  });

  it('H is neither the basepoint nor the identity', () => {
    expect(toHex(pointCompress(generatorH()))).not.toBe(toHex(pointCompress(generatorG())));
    expect(toHex(pointCompress(generatorH()))).not.toBe('00'.repeat(32));
  });

  it('derives the same nullifier base', () => {
    expect(toHex(pointCompress(nullifierBase(VECTORS.eventId, VECTORS.epoch)))).toBe(
      VECTORS.nullifierBase
    );
  });

  it('derives the same commitments', () => {
    const { ringHex } = buildFixture();
    expect(ringHex).toEqual(VECTORS.commitments);
  });

  it('derives the same Merkle root', () => {
    const { ctx } = buildFixture();
    expect(toHex(ctx.merkleRoot)).toBe(VECTORS.merkleRoot);
  });
});

describe('proof conformance with the Rust prover', () => {
  it('produces byte-identical proof bytes', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx, vectorRng('conformance'));
    expect(toHex(encodeProof(proof))).toBe(VECTORS.proof);
  });

  it('produces the same nullifier', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx, vectorRng('conformance'));
    expect(toHex(proof.nullifier)).toBe(VECTORS.nullifier);
  });

  it('encodes the documented header', () => {
    const bytes = fromHex(VECTORS.proof);
    expect(bytes[0]).toBe(PROOF_VERSION);
    expect(bytes[1]).toBe(tierByte(VECTORS.tier));
    expect((bytes[2] << 8) | bytes[3]).toBe(VECTORS.ringSize);
    // header + nullifier + 3 scalar groups
    expect(bytes.length).toBe(4 + 32 + 3 * 32 * VECTORS.ringSize);
  });
});

describe('proof soundness', () => {
  it('accepts an honest proof', () => {
    const { witness, ctx } = buildFixture();
    expect(verifyLocally(prove(witness, ctx), ctx)).toBe(true);
  });

  it('accepts a proof from every ring position', () => {
    const { ring, ctx } = buildFixture();
    for (let i = 0; i < ring.length; i++) {
      const ticket = ticketScalar(`EVENTOPRY-TICKET-${String(i).padStart(3, '0')}`);
      const secret = hashToScalar('eventopry/zkp/v1/secret-scalar', [utf8(`conformance-secret-${i}`)]);
      expect(verifyLocally(prove({ index: i, ticket, secret }, ctx), ctx)).toBe(true);
    }
  });

  it('rejects a tampered response', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    const tampered = { ...proof, zSecret: [...proof.zSecret] };
    tampered.zSecret[witness.index] += BigInt(1);
    expect(verifyLocally(tampered, ctx)).toBe(false);
  });

  it('rejects a tampered challenge', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    const tampered = { ...proof, challenges: [...proof.challenges] };
    tampered.challenges[0] += BigInt(1);
    expect(verifyLocally(tampered, ctx)).toBe(false);
  });

  it('rejects a substituted nullifier', () => {
    // This is the double-spend attack: swap in a fresh nullifier so the
    // already-used one is never presented. It must not verify.
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    const forged = {
      ...proof,
      nullifier: pointCompress(
        computeNullifier(secretScalar(utf8('some-other-secret')), ctx.eventId, ctx.epoch)
      ),
    };
    expect(verifyLocally(forged, ctx)).toBe(false);
  });

  it('rejects an identity nullifier', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    expect(verifyLocally({ ...proof, nullifier: new Uint8Array(32) }, ctx)).toBe(false);
  });

  it('rejects a proof replayed against a different event', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    expect(verifyLocally(proof, { ...ctx, eventId: 'evt_somewhere_else' })).toBe(false);
  });

  it('rejects a proof replayed against a different epoch', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    expect(verifyLocally(proof, { ...ctx, epoch: 'reentry-2' })).toBe(false);
  });

  it('rejects a tier downgrade', () => {
    const { witness, ctx } = buildFixture();
    const proof = prove(witness, ctx);
    expect(verifyLocally(proof, { ...ctx, tier: 'general' })).toBe(false);
  });

  it('refuses to prove with a witness that does not open its commitment', () => {
    const { ctx } = buildFixture();
    expect(() =>
      prove(
        {
          index: 0,
          ticket: ticketScalar('EVENTOPRY-TICKET-000'),
          secret: secretScalar(utf8('wrong-secret')),
        },
        ctx
      )
    ).toThrow(/does not open/);
  });

  it('refuses a witness index outside the ring', () => {
    const { witness, ctx } = buildFixture();
    expect(() => prove({ ...witness, index: 99 }, ctx)).toThrow(/outside the ring/);
  });
});

describe('unlinkability', () => {
  it('produces a stable nullifier across independent proofs', () => {
    // Same ticket, same event: the nullifier must repeat, or double-spend
    // detection cannot work at all.
    const { witness, ctx } = buildFixture();
    const first = prove(witness, ctx);
    const second = prove(witness, ctx);
    expect(toHex(first.nullifier)).toBe(toHex(second.nullifier));
  });

  it('produces unlinkable proof bodies for the same ticket', () => {
    // ...while the proofs themselves must differ, or two check-ins could be
    // tied together by comparing bytes.
    const { witness, ctx } = buildFixture();
    const first = prove(witness, ctx);
    const second = prove(witness, ctx);
    expect(toHex(encodeProof(first))).not.toBe(toHex(encodeProof(second)));
  });

  it('produces a different nullifier per event and per epoch', () => {
    const secret = secretScalar(utf8('a-secret'));
    const base = toHex(pointCompress(computeNullifier(secret, 'evt_a', DEFAULT_EPOCH)));
    expect(toHex(pointCompress(computeNullifier(secret, 'evt_b', DEFAULT_EPOCH)))).not.toBe(base);
    expect(toHex(pointCompress(computeNullifier(secret, 'evt_a', 'reentry-2')))).not.toBe(base);
  });
});

describe('Merkle tree', () => {
  const a = new Uint8Array(32).fill(1);
  const b = new Uint8Array(32).fill(2);
  const c = new Uint8Array(32).fill(3);

  it('is order-sensitive', () => {
    expect(toHex(merkleRoot([a, b]))).not.toBe(toHex(merkleRoot([b, a])));
  });

  it('promotes an odd node rather than duplicating it', () => {
    // Duplicating the last leaf is CVE-2012-2459: two different leaf lists
    // would share a root. Promotion must keep them distinct.
    expect(toHex(merkleRoot([a, b, c]))).not.toBe(toHex(merkleRoot([a, b, c, c])));
  });

  it('returns a single leaf unchanged', () => {
    expect(toHex(merkleRoot([a]))).toBe(toHex(a));
  });

  it('returns all zeros for an empty tree', () => {
    expect(toHex(merkleRoot([]))).toBe('00'.repeat(32));
  });

  it('hashes leaves rather than using commitments directly', () => {
    const commitment = fromHex(VECTORS.commitments[0]);
    expect(toHex(leafHash(commitment))).not.toBe(toHex(commitment));
  });
});

describe('tier metadata', () => {
  it('matches the Rust wire bytes', () => {
    expect(tierByte('general')).toBe(0);
    expect(tierByte('age21plus')).toBe(1);
    expect(tierByte('vip')).toBe(2);
  });

  it('gives VIP a lower ring floor than the general tiers', () => {
    expect(tierMinRing('general')).toBe(8);
    expect(tierMinRing('age21plus')).toBe(8);
    expect(tierMinRing('vip')).toBe(4);
  });

  it('refuses a ring below the tier floor', () => {
    const { ring, witness, ctx } = buildFixture();
    const short = ring.slice(0, 4);
    expect(() =>
      prove(witness, {
        ...ctx,
        ring: short,
        merkleRoot: merkleRootOfCommitments(short.map((m) => m.compressed)),
      })
    ).toThrow(/outside the permitted range/);
  });
});

describe('hex helpers', () => {
  it('round-trips', () => {
    const bytes = new Uint8Array([0, 1, 15, 16, 127, 128, 255]);
    expect(toHex(fromHex(toHex(bytes)))).toBe(toHex(bytes));
  });

  it('rejects odd-length input', () => {
    expect(() => fromHex('abc')).toThrow(/odd-length/);
  });

  it('rejects non-hex characters', () => {
    expect(() => fromHex('zzzz')).toThrow(/non-hex/);
  });
});

describe('generateCheckinProof', () => {
  const secretBytes = utf8('conformance-secret-3');

  function request(overrides: Record<string, unknown> = {}) {
    const { ringHex, ctx } = buildFixture();
    return {
      eventId: VECTORS.eventId,
      tier: VECTORS.tier,
      ringHex,
      merkleRootHex: toHex(ctx.merkleRoot),
      ticketId: 'EVENTOPRY-TICKET-003',
      secretBytes,
      ...overrides,
    };
  }

  it('builds a proof the local verifier accepts', () => {
    const result = generateCheckinProof(request());
    expect(result.witnessIndex).toBe(VECTORS.witnessIndex);
    expect(result.anonymitySetSize).toBe(VECTORS.ringSize);
    expect(result.nullifierHex).toBe(VECTORS.nullifier);
    expect(result.proofHex.length).toBe(2 * (4 + 32 + 3 * 32 * VECTORS.ringSize));
  });

  it('reproduces the Rust proof exactly when given the shared RNG', () => {
    const result = generateCheckinProof(request({ rng: vectorRng('conformance') }));
    expect(result.proofHex).toBe(VECTORS.proof);
  });

  it('defaults the epoch to the check-in epoch', () => {
    const withDefault = generateCheckinProof(request({ rng: vectorRng('conformance') }));
    const explicit = generateCheckinProof(
      request({ epoch: DEFAULT_EPOCH, rng: vectorRng('conformance') })
    );
    expect(withDefault.proofHex).toBe(explicit.proofHex);
  });

  it('rejects a ring that does not match the published root', () => {
    // A narrowed or swapped ring would still produce a provable statement, but
    // with an anonymity set the attacker chose. It has to fail on-device.
    const { ringHex } = buildFixture();
    const narrowed = ringHex.slice(0, 4).concat(ringHex.slice(0, 4));
    expect(() => generateCheckinProof(request({ ringHex: narrowed }))).toThrow(
      /does not reproduce the published Merkle root/
    );
  });

  it('reports a ticket that is not in the set', () => {
    expect(() =>
      generateCheckinProof(request({ ticketId: 'EVENTOPRY-TICKET-999' }))
    ).toThrow(/not in the anonymity set/);
  });

  it('rejects a malformed Merkle root', () => {
    expect(() => generateCheckinProof(request({ merkleRootHex: 'abcd' }))).toThrow(
      /must be 32 bytes/
    );
  });

  it('rejects a ring entry that is not a valid group element', () => {
    const { ringHex } = buildFixture();
    const corrupted = [...ringHex];
    corrupted[0] = 'ff'.repeat(32);
    expect(() => generateCheckinProof(request({ ringHex: corrupted }))).toThrow(
      /not a valid ristretto255 point/
    );
  });
});

describe('findWitnessIndex', () => {
  it('locates a commitment in the ring', () => {
    const { ring } = buildFixture();
    const ticket = ticketScalar('EVENTOPRY-TICKET-005');
    const secret = hashToScalar('eventopry/zkp/v1/secret-scalar', [utf8('conformance-secret-5')]);
    expect(findWitnessIndex(ring, commit(ticket, secret))).toBe(5);
  });

  it('returns -1 when absent', () => {
    const { ring } = buildFixture();
    const absent = commit(ticketScalar('nope'), secretScalar(utf8('nope')));
    expect(findWitnessIndex(ring, absent)).toBe(-1);
  });
});
